- algorithm/category.json
- algorithm/search/binary_search/desc.json
- algorithm/search/binary_search/iterative/code.js
- algorithm/search/binary_search/iterative/data.js
- algorithm/search/binary_search/recursive/code.js
- algorithm/search/binary_search/recursive/data.js
- js/module/array1d.js
- js/module/array2d.js
Added recursive & iterative implementation of binary search.
> Binary search

- algorithm/category.json
- algorithm/sorting/merge/basic/code.js
- algorithm/sorting/merge/basic/data.js
- algorithm/sorting/merge/desc.json
> Add Mergesort

- algorithm/category.json
- algorithm/sorting/heap/basic/code.js
- algorithm/sorting/heap/basic/data.js
- algorithm/sorting/heap/desc.json
> Add Heap Sort

- algorithm/category.json
- algorithm/graph_search/dijkstra/desc.json
- algorithm/graph_search/dijkstra/shortest_path/code.js
- algorithm/graph_search/dijkstra/shortest_path/data.js
Visualization would be better if the tracer was able to display more than one thing a time.
> Dijkstra's algorithm

- algorithm/search/binary_search/recursive/code.js
BinarySearch algorithm visualization change color of  only cell of minIndex, maxIndex and middleIndex.
But, It's hard to know and understand a range through minIndex, maxIndex.
So change color of all cell between minIndex and maxIndex.
> Change intuitively

- algorithm/sorting/heap/basic/code.js
Updated array element at each iteration
> Fix minor bug

- algorithm/sorting/bubble/basic/code.js
- algorithm/sorting/quick/basic/code.js
- algorithm/sorting/selection/basic/code.js
> Sorting time complexity

- algorithm/sorting/bubble/basic/code.js
- algorithm/sorting/quick/basic/code.js
- algorithm/sorting/selection/basic/code.js
Reverts parkjs814/AlgorithmVisualizer#30
Check out the result before sending pull request please 😅
> Revert "Sorting time complexity"

- css/stylesheet.css
@parkjs814 
Continuing #31 
How about this?
Btw please don't close this Pull request. I can update it if you need any more changes..
> Added styled scrollbars

- js/script.js
> Sharing scratch paper

- algorithm/etc/dp/longest_increasing_subsequence/code.js
- algorithm/etc/dp/longest_increasing_subsequence/data.js
As suggested code is modified to accept any array length.
> Modify code to accept any array length

- algorithm/etc/dp/desc.json
- algorithm/etc/dp/max_subarray/code.js
- algorithm/etc/dp/max_subarray/data.js
> Maximum Subarray Sum

- algorithm/category.json
- algorithm/graph_search/bridges/desc.json
- algorithm/graph_search/bridges/naive/code.js
- algorithm/graph_search/bridges/naive/data.js
Implemented the Naive Algorithm
> Bridge-Finding in Undirected Graph

- css/stylesheet.css
- js/script.js
Added minor css updates:
- cursor:pointer when hovering buttons. 
- Improved the layout for headers in the algorithm description and added a border for easier visual separation.
> Css updates

- js/script.js
Update to display carets for algorithm categories, making it easier to see they are dropdown lists.
Also applied [js-beautify](https://github.com/beautify-web/js-beautify) to the `script.js` (this was on accident because my editor does it automatically, but I figured it wouldn't hurt :) )
> Added carets to display and update when toggling algorithm categories

- js/script.js
Added [Source Code Pro](https://github.com/adobe-fonts/source-code-pro) font to the data container and code container.
> Add source code pro font

- js/script.js
> Change caret direction

- algorithm/category.json
Corrected a minor spelling error
> Spelling error

- algorithm/category.json
- algorithm/cryptography/caesar_cipher/basic/code.js
- algorithm/cryptography/caesar_cipher/basic/data.js
- algorithm/cryptography/caesar_cipher/desc.json
Added [Caesar Cipher algorithm](https://en.wikipedia.org/wiki/Caesar_cipher).
Sample run:
> Added caesar cipher algorithm

- js/module/array2d.js
- js/module/weighted_directed_graph.js
- js/tracer_manager.js
Added `refineByType` method, as [discussed here](https://github.com/parkjs814/AlgorithmVisualizer/pull/83#issuecomment-222172921)
> Refine by type method

- algorithm/sorting/merge/bottom_up/code.js
> fix logger text

- js/script.js
Each algorithm has a unique link.
So that when i reload the page or share this link with friends i get this algorithm.
Hope this is helpful :smile:
> add link/hash navigation to algorithms

- algorithm/category.json
- algorithm/sorting/cycle/basic/code.js
- algorithm/sorting/cycle/basic/data.js
- algorithm/sorting/cycle/desc.json
I added cycle sort in sorting algorithms. 
While not the most efficient sorting algorithm cycle sort is unique in that it minimizes write frequency
> Added cycle sort

- js/script.js
Scratch paper link now uses hashes instead of query string, so now link are #scratch-paper rather than ?scratch-paper.
> Fix link hash and scratch paper

- algorithm/graph_search/dijkstra/shortest_path/code.js
> Fix visualization

- algorithm/category.json
- algorithm/graph_search/page_rank/basic/code.js
- algorithm/graph_search/page_rank/basic/data.js
- algorithm/graph_search/page_rank/desc.json
PageRank v1 & v2 were published by Larry and Sergey themselves. Subsequent revisions were done in order to improve indexing. Currently, the directory contains "basic", i.e., Version 1. I'll be following up with 2 soon.
Since Page ranks are decimal numbers, recommended setting is to enlarge the visualization window for complete view.
> Added PageRank Algorithm

- css/stylesheet.css
Hi, I really love the idea of this application and I know it will help all computer science students and peoples who are interested with algorithms. I found a small issue with the application that, when viewing on small laptop screen with resolution 1366x768, the description area got cut at the bottom and it doesn't scroll.
I have fixed the issue by adding "overflow: scroll" to "tab" class. I hope it will help.
> fixed the scrolling issue with tab

- algorithm/cryptography/caesar_cipher/basic/data.js
- algorithm/dp/ugly_numbers/basic/data.js
- algorithm/string/knuth_morris_pratt/substring_search/data.js
This pull request proposes a fix to (#112).
> LogTracer fix

- algorithm/cryptography/caesar_cipher/basic/code.js
Fixed rotation order in caesar cipher where now:
- up means a->z
- down means z->a
> fixed rotation order in Caesar Cipher

- algorithm/sorting/cycle/basic/code.js
fix two ReferenceError ( i and cycleStart) in Sorting > CycleSort
> fix reference error

- algorithm/cryptography/caesar_cipher/basic/code.js
- algorithm/cryptography/caesar_cipher/basic/data.js
> Ceasar cipher fix-Encrypt string with spaces

- algorithm/etc/cellular_automata/cellular_automata/code.js
- algorithm/etc/cellular_automata/cellular_automata/data.js
- algorithm/etc/cellular_automata/desc.json
Implemented cellular automata (with some arbitrary set of rules) and put it in the "Uncategorized" section under Flood Fill.
> implemented cellular automata algorithm

- algorithm/category.json
- algorithm/etc/create_maze/create_maze/code.js
- algorithm/etc/create_maze/create_maze/data.js
- algorithm/etc/create_maze/desc.json
- gulpfile.babel.js
I saw that there isn’t anything on disjoint sets or mazes under the
examples so I implemented the process of making a maze.
I have visualized a maze creation before
(https://github.com/nadr0/Maze). I have always been a fan of
visualizing data structures or algorithms and I though this was the
perfect chance!
My code is rather large but it gets the job done.
> Added Maze creation example

- algorithm/category.json
Sorry, I found one more misspelling. Don't know how I missed it. grep fail
> Correct one more misspelling of Eratosthenes

- js/dom/setup/setup_top_menu.js
Updated `setup_top_menu.js` to change the text displayed on start button from "Start" -> "Reset" after the button is clicked.  The button does the reset job if it is clicked after starting...
Its just a suggestion.. what did you say @parkjs814 ?
> Updated setup_top_menu.js 

- algorithm/string/knuth_morris_pratt/substring_search/data.js
`substring` is now a substring of `string` from `rand(0, 9)` (inclusive) of length 5.
> Ensure substring is a substring in "KMP Substring Search"

- js/create/array2d.js
- js/create/index.js
- js/create/util.js
Bugs fixed
- allows for text & strings in 1D/2D tracers 
- correctly outputs strings in the generated javascript
- automatically clicks the "trace" tab for the user will be in the correct view for seeing the generated tracers.
> Auto generate tracers - fixing bugs

- css/stylesheet.css
- index.html
- js/dom/add_files.js
- the tab buttons have a bottom border when not active
- changed the background color of the tab buttons 
It looks cleaner now since the button and the container both have the same background color. Now the border is one continuous line outlining the buttons and container.
> Tab button css fix

- algorithm/dp/longest_common_subsequence/basic/code.js
The earlier version of the algorithm we got only length of longest common subsequence. Now we can visualize the subsequence.
> Improved visualization for LCS

- algorithm/category.json
- algorithm/sorting/pancake/basic/code.js
- algorithm/sorting/pancake/basic/data.js
- algorithm/sorting/pancake/desc.json
Adding pancake sorting algorithm in sorting category
> add pancake sort

- algorithm/sorting/pancake/basic/code.js
Apparently i was comparing wrong index for flip optimization
> fix flip optimization in pancake sort function

- algorithm/category.json
- algorithm/graph_search/dls/count_descendant/code.js
- algorithm/graph_search/dls/count_descendant/data.js
- algorithm/graph_search/dls/desc.json
- algorithm/graph_search/dls/tree/code.js
- algorithm/graph_search/dls/tree/data.js
Adding depth-limited search to graph search section
> Depth-limited search

- algorithm/tree/binary_search_tree/bst_insert/code.js
- algorithm/tree/binary_search_tree/bst_insert/data.js
- js/module/tracer/directed_graph_construct.js
- js/module/tracer/index.js
Added trace steps to show addition of nodes and how tree is traversed while adding a new node. This will help in resolving issue #213 in my opinion. Please review and let me know your feedback.
Thanks,
Raj
> Tracer to depict addition of nodes in binary search tree

- algorithm/category.json
- algorithm/etc/stable_matching/basic/code.js
- algorithm/etc/stable_matching/basic/data.js
- algorithm/etc/stable_matching/desc.json
Hi!
I love this project, especially now that I'm studying more specifically this algorithms :)
I've added a Stable Match algorithm (alias Gale-Shapley).
Please let me know if I have to made some edits.
> Stable matching algorithm

- algorithm/graph_search/bfs/desc.json
- algorithm/graph_search/bfs/test_bipartiteness/code.js
- algorithm/graph_search/bfs/test_bipartiteness/data.js
> Added BFS bipartiteness algorithm

- algorithm/category.json
- algorithm/number_theory/miller_rabin_primality_test/basic/code.js
- algorithm/number_theory/miller_rabin_primality_test/basic/data.js
- algorithm/number_theory/miller_rabin_primality_test/desc.json
Another algorithm.
This time a probabilistic algorithm :)
> Added Miller-Rabin primality test

- .gitpod.yml
- CONTRIBUTING.md
Hey 👋
This PR adds a small config file for Gitpod. Gitpod launches a ready-to-code dev environment with a single click. The config file automates the installation of dependencies and I have also included the server to run of the same workspace. 
You can give it a try with my fork of repo: https://gitpod.io/#https://github.com/anudeepreddy/algorithm-visualizer
I have tested it on Gitpod and found that 7 Algorithms which require Docker CLI aren't working on gitpod as running a Docker inside a Docker is highly restricted due to security reasons.
It was really fun automating your project to work on Gitpod. Please feel free to contact for any guidance, I am happy to help.
> Add automated dev setup with Gitpod

- src/core/renderers/ScatterRenderer/ScatterRenderer.module.scss
- src/core/renderers/ScatterRenderer/index.js
- src/core/renderers/index.js
- src/core/tracers/ScatterTracer.js
- src/core/tracers/index.js
Hello there!
I'm adding a new visualizer to a new algorithm, which needs an extra scatter chart, so am adding the corresponding tracer and renderer here:
> feat: add ScatterTracer and ScatterRenderer
